In [2]:
import os
if not 'id_0123456789876543210' in locals():
    os.chdir(os.path.split(os.getcwd())[0])
    id_0123456789876543210 = None

In [3]:
import numpy as np

In [4]:
import pandas as pd
import re

from src.utilitz.excel import decode_column, read_excel_table

In [6]:
data = read_excel_table('data/prueba.xlsx',
                        usecols='B:H',
                        findheaders=True,
                        checkcol='B',
                        patterncol=r'\d+')

In [10]:
data[2]

,Unnamed: 1,ProductSubcategory,Product,ProductColor,Model,Unnamed: 6,Unnamed: 7
0,1,Road Bikes,"Road-150 Red, 62",Red,Road-150,NaN,NaN
1,2,Mountain Bikes,"Mountain-100 Silver, 44",Silver,Mountain-100,NaN,NaN
2,2,Mountain Bikes,"Mountain-100 Silver, 44",Silver,Mountain-100,NaN,NaN
3,3,Road Bikes,"Road-650 Black, 62",Black,Road-650,NaN,NaN
4,3,Mountain Bikes,"Mountain-100 Silver, 44",Silver,Mountain-100,NaN,NaN
...,...,...,...,...,...,...,...
1196,599,Road Bikes,"Road-150 Red, 48",Red,Road-150,NaN,NaN
1197,600,Road Bikes,"Road-150 Red, 52",Red,Road-150,NaN,NaN
1198,600,Road Bikes,"Road-650 Black, 48",Black,Road-650,NaN,NaN
1199,601,Mountain Bikes,"Mountain-100 Black, 42",Black,Mountain-100,NaN,NaN
1200,601,Mountain Bikes,"Mountain-100 Black, 44",Black,Mountain-100,NaN,NaN